---
version: 1

root:
  # Filtering of messages by level is done at the handler level by using NOTSET
  # on the root logger to emit everything.  This lets us keep console output
  # readable while emitting verbose output to alternate handlers.
  level: NOTSET
  handlers:
    - console
    - syslog

loggers:
  # The SmartyStreets library uses urllib3, which produces DEBUG messages that
  # can contain sensitive data.  Suppress those at its package logger.
  urllib3:
    level: INFO

handlers:
  console:
    class: logging.StreamHandler
    level: !coalesce
      - !LOG_LEVEL
      - INFO
    formatter: console

  # This handler emits all log levels; filtering is more usefully done by
  # syslog itself.
  syslog:
    class: id3c.logging.handlers.SysLogUnixSocketHandler
    level: NOTSET
    formatter: syslog

formatters:
  console:
    format: "[%(asctime)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  syslog:
    format: "id3c[%(process)s] %(name)s %(levelname)s: %(message)s"
